### ISSUE TITLE
Save dates in database in UTC format

### ISSUE THREAD

**Issue by jenslw** [partidodev/partido-server#18]
All dates should be saved in UTC explicitly.

**Comment by jonathanharr92** [comment]
I'd like to help. I figure from watching your code, just putting the current date will suffice. Perhaps add some sort of validator bean on dates.

However, I can't start your project. I'm prohibited from visiting the localhost URL. But my postgres has recieved your tables. (Also, per auto, a user with my db username was created in the table)

**Comment by jenslw** [comment]
Hi @jonathanharr92, welcome :) If you see an error visiting localhost:8080 after starting the server, everything is okay.

The server has only one endpoint to be visible in a browser- only for verifying user accounts. All other operations are done using the Partido Client App or, for local development, a REST client like Insomnia or Postman.

I just added a section to the Readme with information about this. It would be more useful to have some API docs but I still didn't made them. I'll look on doing this as soon as possible.

In the meantime you can use the Insomnia REST tool (https://github.com/Kong/insomnia). You just need to import [this file](https://gist.github.com/jenslw/11f68753769e49423662a85e7c64341f) into the tool and all important endpoints can easily be called.

**Comment by jonathanharr92** [comment]
Awesome, I'm used to Postman, so will look into it via PostMan then. 

Also, I will do some changes to the UsersApi. I take it you need validation that the current time and date of registration is in UTC right?

**Comment by jonathanharr92** [comment]
The file, can it be used in Postman as well? It's an authorization file or?

**Comment by jenslw** [comment]
Yes, the registration date/time should be saved in UTC, as well as the creation date of bills and groups. I'm not sure if the server already saves UTC Dates automatically or if the client app is sending wrong timestamps to the server (when creating a new entry in a group, the user can change the entry's date).

If you find the issue and know a solution, great ;)

**Comment by jenslw** [comment]
> The file, can it be used in Postman as well? It's an authorization file or?

I know that Insomnia can import Postman files but I have no idea if Postman Kan import an Insomnia file. The file contains just a workspace with sample data and the needed REST paths.

**Comment by jonathanharr92** [comment]
Bro, I'm using a custom SQL editor from work.
And I can't drop table User. I think it's a bad idea to call tables by reserved SQL names. (Or, it's the editor I'm using but it's a tool for db management and testing)

**Comment by jenslw** [comment]
I didn't get any issues with this until now - but I was using pgAdmin only to look into the db. You're right, we should maybe automatically prefix all tables automatically using a custom naming strategy or explicitly name tables in the corresponding classes. I'll create a new issue for that task 👌

**Comment by jenslw** [comment]
> And I can't drop table User

As a workaround, does quoting the table name with backticks ` work to drop it?

**Comment by jonathanharr92** [comment]
Not sure. I just made a new table. I'll push this commit and you can judge what's best.
However, for simplicity, just renaming it to partido_user could be easier to reduce complexity?

**Comment by jenslw** [comment]
I have no idea how much more complex a custom naming strategy will be but for now it's completely okay to just rename the table explicitly 👍

**Comment by jonathanharr92** [comment]
Well I guess it's equally valid. I just figure, it might get someone else stuck too for unnecessary reasons.
So I tried to push now, and it says "Remote: Permission to ...... unable to access (url) returned error 403" Hmm. Git is so amazing:p Do I have permission to post?

Also, that issue will be resolved through my branch since renaming the table will solve the problem 👍

**Comment by jonathanharr92** [comment]
![bild](https://user-images.githubusercontent.com/49676040/93017707-089e9c00-f5cb-11ea-8338-5fda94bdd0f8.png)
I suppose I don't have permission? But not so sure. Haven't used Github as a repository user, only created my own repositories. :)

**Comment by jenslw** [comment]
On GitHub you normally have to fork other projects/repositories before you can contribute to them.

The workflow on GitHub is something like:
- fork a project/repository to get a copy in your own account
- checkout a branch from the fork or create a new branch based on the fork
- push some code changes to it
- create a Pull request from your branch to the original repository

**Comment by jonathanharr92** [comment]
Ohh.. So my branch is tied to this git repo now then? I can't get it to my fork unless I paste everything in there then? :/

**Comment by jenslw** [comment]
There is another way you can fix this without copy pasting everything ;)

Create a fork and change the upstream of your local repository to use your new fork's url:

```
git branch branch_name --set-upstream-to your_new_remote/branch_name
```

**Comment by jonathanharr92** [comment]
There!
I had to do it the stupid way.. Atleast I'll never not fork now since I've felt some GitHub pain. Hehe.

**Comment by jonathanharr92** [comment]
Oh and pr is up as you can see. Hope its sufficent.

**Comment by jenslw** [comment]
Thank you! I'll look at it later because there are a few changes ^^
